### ISSUE TITLE
Enable checkbox not working

### ISSUE THREAD

**Issue by hkclark** [opto/glodaquilla#1]
Hi, thanks for making this!  I installed it and the "Options" dialog did open a full-window screen with the checkbox and "Enable GlodaQuilla inherited...", but there don't appear to be an OK or Submit button.  If I close the tab and reopen it, it comes back unchecked.  Thoughts?  Thanks.

**Comment by opto** [comment]
it needs the right css file. Working on my system, but upload to git has a problem .... sorry.
The TB addons 57 website describes which css, if you want to do it yourself in the meantime.

**Comment by hkclark** [comment]
OK, thank you very much.

**Comment by opto** [comment]
has been updated
